# Generated by Django 4.1 on 2022-08-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_cookbook_qty_alter_recipe_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookbook',
            old_name='ing_id',
            new_name='ing',
        ),
        migrations.RenameField(
            model_name='cookbook',
            old_name='rec_id',
            new_name='rec',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_id',
            new_name='iid',
        ),
        migrations.RenameField(
            model_name='mealplan',
            old_name='rec_col_id',
            new_name='rec_col',
        ),
        migrations.RenameField(
            model_name='mealplan',
            old_name='rec_id',
            new_name='rid',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_id',
            new_name='rid',
        ),
        migrations.RenameField(
            model_name='recipecollection',
            old_name='rec_col_id',
            new_name='rcid',
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
