# Generated by Django 4.1 on 2022-08-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_rename_ing_id_cookbook_ing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecollection',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
