# Generated by Django 4.1 on 2022-08-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_alter_recipecollection_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecollection',
            name='created_date',
            field=models.DateField(),
        ),
    ]
