# Generated by Django 4.1 on 2022-09-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_alter_recipecollection_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
